feat(virtualization): add stop,start,restart commands
deckhouse/deckhouse-cli pull request #21
Opened 2024-06-26 19:36 UTC by yaroslavborbat

## Description
Added stop,start, restart subcommands for `d8 virtualization`

2024-06-26 20:28 UTC, diafour commented on internal/virtualization/cmd/powerstate/vmop/vmop.go
> +	return fmt.Sprintf("VirtualMachineOperation %q compleated. phase=%q, reason=%q, message=%q\n", key.String(), phase, vmop.Status.FailureReason, vmop.Status.FailureMessage)
```suggestion
	return fmt.Sprintf("VirtualMachineOperation %q completed. phase=%q, reason=%q, message=%q\n", key.String(), phase, vmop.Status.FailureReason, vmop.Status.FailureMessage)
```

2024-06-26 20:34 UTC, diafour commented on internal/virtualization/cmd/powerstate/vmop/vmop.go
> +	return fmt.Sprintf("VirtualMachineOperation %q compleated. phase=%q, reason=%q, message=%q\n", key.String(), phase, vmop.Status.FailureReason, vmop.Status.FailureMessage)
These messages lacks operation type, i.e. start, stop.

```
VirtualMachineOperation "my-super-important-host-12eqw" completed. phase=Completed, reason=, message=
```
This is not informative, it is better to print operation type:

```
VirtualMachine "my-super-important-host" started. VirtualMachineOperation "my-super-important-host-12eqw" completed. 
```

Also, it seems "completed" message should not print phase, reason, and message, but "not completed" should print reason and message.

2024-06-26 20:36 UTC, diafour commented on internal/virtualization/cmd/powerstate/vmop/vmop.go
> +	return vmop.Status.Phase == v1alpha2.VMOPPhaseCompleted || vmop.Status.Phase == v1alpha2.VMOPPhaseFailed
Oh, failed is completed. It gives misleading messages in generateMsg.

2024-06-26 20:37 UTC, diafour commented on internal/virtualization/cmd/powerstate/powerstate.go
> +	Timeout time.Duration
Timeout is not used. May be delete it?

2024-06-27 07:03 UTC, yaroslavborbat commented on internal/virtualization/cmd/powerstate/powerstate.go
> +	Timeout time.Duration
No, we create a context using this timeout

2024-06-27 07:31 UTC, yaroslavborbat commented on internal/virtualization/cmd/powerstate/vmop/vmop.go
> +	return vmop.Status.Phase == v1alpha2.VMOPPhaseCompleted || vmop.Status.Phase == v1alpha2.VMOPPhaseFailed
The method has been renamed to isFinished and is no used in the generateMsg

2024-07-19 10:23 UTC, diafour requested changes

2024-07-19 10:23 UTC, diafour commented on internal/virtualization/cmd/powerstate/vmop/vmop.go
> +		sb.WriteString("in progress. ")
It is much clearer now! But "in progress" message is noisy:

> VirtualMachine "my-vm" in progress. VirtualMachineOperation "my-vm-qwd23" was not finished. phase=InProgress.

I propose to add operation type and add descriptions for Pending and InProgress phases (see next comment):

> VirtualMachine "my-vm" stopping. VirtualMachineOperation "my-vm-qwd23" is in progress.

> VirtualMachine "my-vm" starting. VirtualMachineOperation "my-vm-qwd23" pending.


```suggestion
		switch vmop.Spec.Type {
		case v1alpha2.VMOPOperationTypeStart:
			sb.WriteString("starting. ")
		case v1alpha2.VMOPOperationTypeStop:
			sb.WriteString("stopping. ")
		case v1alpha2.VMOPOperationTypeRestart:
			sb.WriteString("restarting. ")
		}
```

2024-07-19 10:23 UTC, diafour commented on internal/virtualization/cmd/powerstate/vmop/vmop.go
> +		sb.WriteString(fmt.Sprintf("was not finished. phase=%q.", phase))
```suggestion
	case v1alpha2.VMOPPhasePenging:
		sb.WriteString("pending.")
	case v1alpha2.VMOPPhaseInProgress:
		sb.WriteString("in progress.")
	case v1alpha2.VMOPPhaseCompleted:
		sb.WriteString("completed.")
	case v1alpha2.VMOPPhaseFailed:
		sb.WriteString(fmt.Sprintf("failed. reason=%q, message=%q.", vmop.Status.FailureReason, vmop.Status.FailureMessage))
	default:
		sb.WriteString(fmt.Sprintf(" phase=%q.", phase))
```

2024-07-19 10:50 UTC, diafour approved these changes

2024-07-26 15:50 UTC, mvasl requested changes

2024-07-26 15:50 UTC, mvasl commented on internal/virtualization/cmd/powerstate/start.go
> +		Short:   strings.Title(start) + " a virtual machine.",
Title is deprecated
https://github.com/golang/go/issues/48367

2024-07-26 15:50 UTC, mvasl commented on internal/virtualization/cmd/powerstate/restart.go
> +		Short:   strings.Title(restart) + " a virtual machine.",
Title is deprecated
https://github.com/golang/go/issues/48367

2024-07-26 15:50 UTC, mvasl commented on internal/virtualization/cmd/powerstate/stop.go
> +		Short:   strings.Title(stop) + " a virtual machine.",
Title is deprecated
https://github.com/golang/go/issues/48367

2024-07-30 09:21 UTC, yaroslavborbat commented on internal/virtualization/cmd/powerstate/start.go
> +		Short:   strings.Title(start) + " a virtual machine.",
fixed

2024-07-30 09:21 UTC, yaroslavborbat commented on internal/virtualization/cmd/powerstate/stop.go
> +		Short:   strings.Title(stop) + " a virtual machine.",
fixed

2024-07-30 09:21 UTC, yaroslavborbat commented on internal/virtualization/cmd/powerstate/restart.go
> +		Short:   strings.Title(restart) + " a virtual machine.",
fixed

2024-07-30 09:30 UTC, mvasl approved these changes

2024-07-30 09:34 UTC, merged