refactor(virtualization): lifecycle wait flag behavior
deckhouse/deckhouse-cli pull request #58
Opened 2024-11-15 15:37 UTC by danilrwx

2024-11-19 07:49 UTC, yaroslavborbat approved these changes

2024-11-19 07:49 UTC, yaroslavborbat commented on internal/virtualization/cmd/lifecycle/lifecycle.go
> +		fmt.Sprintf("--%s, -%s: Set this flag for create operation only.", waitFlag, waitFlagShort))
```suggestion
		fmt.Sprintf("--%s, -%s: Set this flag for create operation only.", createOnlyFlag, createOnlyFlagShort))
```

2024-11-19 08:38 UTC, mvasl requested changes

2024-11-19 08:38 UTC, mvasl commented on internal/virtualization/cmd/lifecycle/lifecycle.go
> -	Evict(ctx context.Context, name, namespace string, wait bool) (msg string, err error)
Have you considered using functional options pattern here to avoid constantly changing the interface? I see there is already the `Options` type available, should be straightforward to implement.

https://golang.cafe/blog/golang-functional-options-pattern.html

2024-11-19 08:38 UTC, mvasl commented on internal/virtualization/cmd/lifecycle/vmop/vmop.go
> +	} else {
`else` is redundant here. Consider following the return early pattern.

2024-11-19 09:11 UTC, danilrwx commented on internal/virtualization/cmd/lifecycle/vmop/vmop.go
> +	} else {
fixed

2024-11-19 12:16 UTC, danilrwx commented on internal/virtualization/cmd/lifecycle/lifecycle.go
> -	Evict(ctx context.Context, name, namespace string, wait bool) (msg string, err error)
Removed the options from the interface, but don't really like the vmop dependency, maybe I should get rid of it completely? For example, inject an empty vmop, and add setters for options to the interface

2024-11-19 13:05 UTC, danilrwx commented on internal/virtualization/cmd/lifecycle/lifecycle.go
> -	Evict(ctx context.Context, name, namespace string, wait bool) (msg string, err error)
or remove interface and merge vmop package

2024-11-27 11:05 UTC, mvasl approved these changes

2024-11-27 11:06 UTC, merged