feat(virtualization): serial/vnc reconnect
deckhouse/deckhouse-cli pull request #67
Opened 2024-12-02 09:27 UTC by danilrwx

2024-12-09 09:16 UTC, yaroslavborbat approved these changes

2024-12-09 13:54 UTC, mvasl requested changes

2024-12-09 13:54 UTC, mvasl commented on internal/virtualization/cmd/console/console.go
> +			if e, ok := err.(*websocket.CloseError); ok && e.Code == websocket.CloseGoingAway {
Use of https://pkg.go.dev/errors#As is considered the best practice for such cases. You can also check error codes after matching error type wiat plain `switch`, which will be more readable

2024-12-09 13:54 UTC, mvasl commented on internal/virtualization/cmd/vnc/vnc.go
> +			if e, ok := err.(*websocket.CloseError); ok && e.Code == websocket.CloseGoingAway {
Same as above

2024-12-10 07:23 UTC, danilrwx commented on internal/virtualization/cmd/vnc/vnc.go
> +			if e, ok := err.(*websocket.CloseError); ok && e.Code == websocket.CloseGoingAway {
fixed

2024-12-10 07:23 UTC, danilrwx commented on internal/virtualization/cmd/console/console.go
> +			if e, ok := err.(*websocket.CloseError); ok && e.Code == websocket.CloseGoingAway {
fixed

2024-12-10 09:22 UTC, mvasl approved these changes

2024-12-10 09:28 UTC, merged